[package]
name = "dmx-server"
version = "0.1.0"
edition = "2021"

[dependencies]
dmx-shared = { path = "../dmx-shared" }
rust_dmx = { git = "https://github.com/JoNil/rust-dmx.git" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tungstenite = { version = ">=0.17, <=0.20" }
